---
title: "Caribou Dashboard"
format: dashboard
---

```{r}
#| echo: false
#| warning: false
#| message: false
library(sf)
library(terra)
library(tidyverse)
library(maptiles)

opentopomap <- create_provider(
  name = "otm",
  url = "https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png",
  sub = c("a", "b", "c"),
  citation = "map data: @ OpenStreetMap contributors, SRTM | map style: @ OpenTopoMap (CC-BY-SA)"
)

bnd <- st_read('data/yt_caribou.gpkg', 'mcp_buff15k', quiet=TRUE) |>
  st_transform(4326)
bnd <- vect(bnd)
bg <- get_tiles(ext(bnd), provider=opentopomap)
bg <- crop(bg, bnd)
```

#  {.sidebar}

**Github**

- [Analysis workbook](https://beaconsproject.github.io/little_rancheria)

**Bookmarks**


# Habitat

## Row {height=50%}

### Column {width=50%}

```{r}
#| title: Early winter
r <- rast("data/predict30/randomforest/earlywintermap.tif") |>
  project("+proj=longlat +datum=WGS84")
plotRGB(bg)
plot(r, alpha=0.75, add=TRUE)
lines(bnd, col="black", lwd=2)
```

### Column {width=50%}

```{r}
#| title: Late winter
r <- rast("data/predict30/randomforest/latewintermap.tif") |>
  project("+proj=longlat +datum=WGS84")
plotRGB(bg)
plot(r, alpha=0.75, add=TRUE)
lines(bnd, col="black", lwd=2)
```

## Row {height=50%}

### Column {width=50%}

```{r}
#| title: Summer
r <- rast("data/predict30/randomforest/summermap.tif") |>
  project("+proj=longlat +datum=WGS84")
plotRGB(bg)
plot(r, alpha=0.75, add=TRUE)
lines(bnd, col="black", lwd=2)
```

### Column {width=50%}

```{r}
#| title: Fall rut
r <- rast("data/predict30/randomforest/fallrutmap.tif") |>
  project("+proj=longlat +datum=WGS84")
plotRGB(bg)
plot(r, alpha=0.75, add=TRUE)
lines(bnd, col="black", lwd=2)
```
