---
title: "References"
---

Anderson, M.G., Barnett, A., Clark, M., Prince, J., Olivero Sheldon, A. and Vickery B. 2016. Resilient and Connected Landscapes for Terrestrial Conservation. The Nature Conservancy, Eastern Conservation Science, Eastern Regional Office. Boston, MA.

Dobrowski et al. 2021. Protected-area targets could be undermined by climate change-driven shifts in ecoregions and biomes. Communications Earth & Environment 2(1):1-11.

Keeley et al. 2021. Connectivity metrics for conservation planning and monitoring. Biological Conservation 255:109088.

O'Malley 2024. Machine learning allows for large‑scale habitat prediction.

Parks et al. 2020. Human land uses reduce climate connectivity across North America. Global Change Biology 26(5):2944-2955.

Rudolph 2019.

Saura, S., Bastin, L., Battistella, L., Mandrici, A., & Dubois, G. 2017. Protected areas in the world's ecoregions: How well connected are they? Ecological Indicators 76:144-158.

Tompalski 2024 (example of using FRI data)

Ward et al. 2020. Just ten percent of the global terrestrial protected area network is structurally connected via intact land. Nature Communications.
