---
title: tidysdm models
execute:
  freeze: auto
  echo: true
---

## Introduction

https://evolecolgroup.github.io/tidysdm/articles/a0_tidysdm_overview.html

```{r}
#| echo: false
#| message: false
library(sf)
library(terra)
library(report)
library(tidysdm)
library(tidyterra)
library(tidyverse)
set.seed(5228)
```

Read rasters that will be needed for generating prediction maps.

```{r}
#Select a season or comment out line 20
seasons <- c('earlywinter', 'latewinter', 'summer', 'fallrut')
i <- seasons[1]
nsize = 10000
```

## Read raster covariates
```{r}
landcov <- rast('../data/raster30/landcov.tif')
topo <- rast('../data/raster30/topo.tif')
fires <- rast('../data/raster30/fires.tif')
dist2line <- rast('../data/raster30/dist2line.tif')
names(dist2line) <- "dist2line"
dist2poly <- rast('../data/raster30/dist2poly.tif')
names(dist2poly) <- "dist2poly"
rasters <- c(landcov, topo, fires, dist2line, dist2poly)
names(rasters)
```

## Read climate data
```{r}
bio <- rast('../data/raster1000/bio.tif')
```

## Run models for each season

```{r}
for (sea in seasons) {
  cat('Processing', sea, '...\n'); flush.console()
  
  # Prepare data
  gps <- st_read('../data/yt_caribou.gpkg', 'gps_vars', quiet=TRUE) |>
    filter(season==sea) |>
    select(individual, occurrence) |>
    thin_by_cell(raster = bio[[1]])
  gps1 <- filter(gps, occurrence==1)
  gps0 <- filter(gps, occurrence==0)
  
  dta <- gps |>
    st_drop_geometry() |>
    mutate(pa=occurrence, fpa=as.factor(occurrence)) |>
    mutate(occurrence=NULL) |>
    #sample_n(nsize) |>
    as.data.frame()

  plot(rasters$elevation)
  points(gps1)
```
